# coding: utf-8

"""
    ImageService API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from forester_client.models.appliance_service_find_response import ApplianceServiceFindResponse

class TestApplianceServiceFindResponse(unittest.TestCase):
    """ApplianceServiceFindResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApplianceServiceFindResponse:
        """Test ApplianceServiceFindResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApplianceServiceFindResponse`
        """
        model = ApplianceServiceFindResponse()
        if include_optional:
            return ApplianceServiceFindResponse(
                appliance = forester_client.models.appliance.Appliance(
                    id = 1.337, 
                    name = '', 
                    kind = 1.337, 
                    uri = '', )
            )
        else:
            return ApplianceServiceFindResponse(
        )
        """

    def testApplianceServiceFindResponse(self):
        """Test ApplianceServiceFindResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
