# coding: utf-8

"""
    ImageService API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from forester_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_rpc_appliance_service_create_post(self) -> None:
        """Test case for rpc_appliance_service_create_post

        """
        pass

    def test_rpc_appliance_service_delete_post(self) -> None:
        """Test case for rpc_appliance_service_delete_post

        """
        pass

    def test_rpc_appliance_service_enlist_post(self) -> None:
        """Test case for rpc_appliance_service_enlist_post

        """
        pass

    def test_rpc_appliance_service_find_post(self) -> None:
        """Test case for rpc_appliance_service_find_post

        """
        pass

    def test_rpc_appliance_service_list_post(self) -> None:
        """Test case for rpc_appliance_service_list_post

        """
        pass

    def test_rpc_image_service_create_post(self) -> None:
        """Test case for rpc_image_service_create_post

        """
        pass

    def test_rpc_image_service_delete_post(self) -> None:
        """Test case for rpc_image_service_delete_post

        """
        pass

    def test_rpc_image_service_find_post(self) -> None:
        """Test case for rpc_image_service_find_post

        """
        pass

    def test_rpc_image_service_get_by_id_post(self) -> None:
        """Test case for rpc_image_service_get_by_id_post

        """
        pass

    def test_rpc_image_service_list_post(self) -> None:
        """Test case for rpc_image_service_list_post

        """
        pass

    def test_rpc_snippet_service_create_post(self) -> None:
        """Test case for rpc_snippet_service_create_post

        """
        pass

    def test_rpc_snippet_service_delete_post(self) -> None:
        """Test case for rpc_snippet_service_delete_post

        """
        pass

    def test_rpc_snippet_service_edit_post(self) -> None:
        """Test case for rpc_snippet_service_edit_post

        """
        pass

    def test_rpc_snippet_service_find_post(self) -> None:
        """Test case for rpc_snippet_service_find_post

        """
        pass

    def test_rpc_snippet_service_list_post(self) -> None:
        """Test case for rpc_snippet_service_list_post

        """
        pass

    def test_rpc_system_service_acquire_post(self) -> None:
        """Test case for rpc_system_service_acquire_post

        """
        pass

    def test_rpc_system_service_boot_local_post(self) -> None:
        """Test case for rpc_system_service_boot_local_post

        """
        pass

    def test_rpc_system_service_boot_network_post(self) -> None:
        """Test case for rpc_system_service_boot_network_post

        """
        pass

    def test_rpc_system_service_find_post(self) -> None:
        """Test case for rpc_system_service_find_post

        """
        pass

    def test_rpc_system_service_kickstart_post(self) -> None:
        """Test case for rpc_system_service_kickstart_post

        """
        pass

    def test_rpc_system_service_list_post(self) -> None:
        """Test case for rpc_system_service_list_post

        """
        pass

    def test_rpc_system_service_logs_post(self) -> None:
        """Test case for rpc_system_service_logs_post

        """
        pass

    def test_rpc_system_service_register_post(self) -> None:
        """Test case for rpc_system_service_register_post

        """
        pass

    def test_rpc_system_service_release_post(self) -> None:
        """Test case for rpc_system_service_release_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
