# coding: utf-8

"""
    Forester API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from forester_client.models.system_service_rename_request import SystemServiceRenameRequest

class TestSystemServiceRenameRequest(unittest.TestCase):
    """SystemServiceRenameRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SystemServiceRenameRequest:
        """Test SystemServiceRenameRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SystemServiceRenameRequest`
        """
        model = SystemServiceRenameRequest()
        if include_optional:
            return SystemServiceRenameRequest(
                pattern = '',
                new_name = ''
            )
        else:
            return SystemServiceRenameRequest(
        )
        """

    def testSystemServiceRenameRequest(self):
        """Test SystemServiceRenameRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
