# coding: utf-8

"""
    ImageService API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from forester_client.models.error_webrpc_endpoint import ErrorWebrpcEndpoint

class TestErrorWebrpcEndpoint(unittest.TestCase):
    """ErrorWebrpcEndpoint unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ErrorWebrpcEndpoint:
        """Test ErrorWebrpcEndpoint
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ErrorWebrpcEndpoint`
        """
        model = ErrorWebrpcEndpoint()
        if include_optional:
            return ErrorWebrpcEndpoint(
                error = 'WebrpcEndpoint',
                code = 0,
                msg = 'endpoint error',
                cause = '',
                status = 400
            )
        else:
            return ErrorWebrpcEndpoint(
                error = 'WebrpcEndpoint',
                code = 0,
                msg = 'endpoint error',
                status = 400,
        )
        """

    def testErrorWebrpcEndpoint(self):
        """Test ErrorWebrpcEndpoint"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
