# coding: utf-8

"""
    Forester API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
from inspect import getfullargspec
import json
import pprint
import re  # noqa: F401

from typing import Any, List, Optional
from pydantic import BaseModel, Field, StrictStr, ValidationError, field_validator
from forester_client.models.error_webrpc_bad_method import ErrorWebrpcBadMethod
from forester_client.models.error_webrpc_bad_request import ErrorWebrpcBadRequest
from forester_client.models.error_webrpc_bad_route import ErrorWebrpcBadRoute
from forester_client.models.error_webrpc_endpoint import ErrorWebrpcEndpoint
from forester_client.models.error_webrpc_request_failed import ErrorWebrpcRequestFailed
from typing import Union, Any, List, TYPE_CHECKING, Optional, Dict
from typing_extensions import Literal
from pydantic import StrictStr, Field
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

RPCIMAGESERVICECREATEPOST4XXRESPONSE_ONE_OF_SCHEMAS = ["ErrorWebrpcBadMethod", "ErrorWebrpcBadRequest", "ErrorWebrpcBadRoute", "ErrorWebrpcEndpoint", "ErrorWebrpcRequestFailed"]

class RpcImageServiceCreatePost4XXResponse(BaseModel):
    """
    RpcImageServiceCreatePost4XXResponse
    """
    # data type: ErrorWebrpcEndpoint
    oneof_schema_1_validator: Optional[ErrorWebrpcEndpoint] = None
    # data type: ErrorWebrpcRequestFailed
    oneof_schema_2_validator: Optional[ErrorWebrpcRequestFailed] = None
    # data type: ErrorWebrpcBadRoute
    oneof_schema_3_validator: Optional[ErrorWebrpcBadRoute] = None
    # data type: ErrorWebrpcBadMethod
    oneof_schema_4_validator: Optional[ErrorWebrpcBadMethod] = None
    # data type: ErrorWebrpcBadRequest
    oneof_schema_5_validator: Optional[ErrorWebrpcBadRequest] = None
    actual_instance: Optional[Union[ErrorWebrpcBadMethod, ErrorWebrpcBadRequest, ErrorWebrpcBadRoute, ErrorWebrpcEndpoint, ErrorWebrpcRequestFailed]] = None
    one_of_schemas: List[str] = Literal["ErrorWebrpcBadMethod", "ErrorWebrpcBadRequest", "ErrorWebrpcBadRoute", "ErrorWebrpcEndpoint", "ErrorWebrpcRequestFailed"]

    model_config = {
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = RpcImageServiceCreatePost4XXResponse.model_construct()
        error_messages = []
        match = 0
        # validate data type: ErrorWebrpcEndpoint
        if not isinstance(v, ErrorWebrpcEndpoint):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ErrorWebrpcEndpoint`")
        else:
            match += 1
        # validate data type: ErrorWebrpcRequestFailed
        if not isinstance(v, ErrorWebrpcRequestFailed):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ErrorWebrpcRequestFailed`")
        else:
            match += 1
        # validate data type: ErrorWebrpcBadRoute
        if not isinstance(v, ErrorWebrpcBadRoute):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ErrorWebrpcBadRoute`")
        else:
            match += 1
        # validate data type: ErrorWebrpcBadMethod
        if not isinstance(v, ErrorWebrpcBadMethod):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ErrorWebrpcBadMethod`")
        else:
            match += 1
        # validate data type: ErrorWebrpcBadRequest
        if not isinstance(v, ErrorWebrpcBadRequest):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ErrorWebrpcBadRequest`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in RpcImageServiceCreatePost4XXResponse with oneOf schemas: ErrorWebrpcBadMethod, ErrorWebrpcBadRequest, ErrorWebrpcBadRoute, ErrorWebrpcEndpoint, ErrorWebrpcRequestFailed. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in RpcImageServiceCreatePost4XXResponse with oneOf schemas: ErrorWebrpcBadMethod, ErrorWebrpcBadRequest, ErrorWebrpcBadRoute, ErrorWebrpcEndpoint, ErrorWebrpcRequestFailed. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: dict) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into ErrorWebrpcEndpoint
        try:
            instance.actual_instance = ErrorWebrpcEndpoint.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ErrorWebrpcRequestFailed
        try:
            instance.actual_instance = ErrorWebrpcRequestFailed.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ErrorWebrpcBadRoute
        try:
            instance.actual_instance = ErrorWebrpcBadRoute.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ErrorWebrpcBadMethod
        try:
            instance.actual_instance = ErrorWebrpcBadMethod.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ErrorWebrpcBadRequest
        try:
            instance.actual_instance = ErrorWebrpcBadRequest.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into RpcImageServiceCreatePost4XXResponse with oneOf schemas: ErrorWebrpcBadMethod, ErrorWebrpcBadRequest, ErrorWebrpcBadRoute, ErrorWebrpcEndpoint, ErrorWebrpcRequestFailed. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into RpcImageServiceCreatePost4XXResponse with oneOf schemas: ErrorWebrpcBadMethod, ErrorWebrpcBadRequest, ErrorWebrpcBadRoute, ErrorWebrpcEndpoint, ErrorWebrpcRequestFailed. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        to_json = getattr(self.actual_instance, "to_json", None)
        if callable(to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Dict:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        to_dict = getattr(self.actual_instance, "to_dict", None)
        if callable(to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


